Int8Array, Int16Array, Int32Array, FloatArray, DoubleArray, SymbolArray

Inherits from: Object : Collection : SequenceableCollection : ArrayedCollection : RawArray

These classes implement arrays whose indexed slots are all of the same type.

Int8Array - 8 bit integer
Int16Array - 16 bit integer
Int32Array - 32 bit integer
FloatArray - 32 bit floating point
DoubleArray - 64 bit floating point
SymbolArray - symbols



